[project]
name = "redaction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "azure-ai-textanalytics>=5.3.0",
    "dotenv>=0.9.9",
]
